// Generated by dts-bundle-generator v9.5.1

export declare class AlAccordion extends HTMLElement {
	static get observedAttributes(): string[];
	constructor();
	connectedCallback(): void;
	disconnectedCallback(): void;
	get multiple(): boolean;
	set multiple(value: boolean);
	attributeChangedCallback(): void;
	private handleToggle;
	private updateItems;
}
export declare class AlAccordionItem extends HTMLElement {
	static get observedAttributes(): string[];
	private headerButton;
	constructor();
	connectedCallback(): void;
	disconnectedCallback(): void;
	get title(): string;
	set title(value: string);
	get open(): boolean;
	set open(value: boolean);
	attributeChangedCallback(name: string): void;
	toggle(): void;
	setOpen(open: boolean): void;
}
export declare class AlButton extends HTMLElement {
	static get observedAttributes(): string[];
	constructor();
	get variant(): string;
	set variant(value: string);
	get size(): string;
	set size(value: string);
	get disabled(): boolean;
	set disabled(value: boolean);
	get loading(): boolean;
	set loading(value: boolean);
	get fullWidth(): boolean;
	set fullWidth(value: boolean);
	connectedCallback(): void;
	attributeChangedCallback(): void;
	private render;
}
export type CloseReason = "close-button" | "backdrop" | "escape" | "programmatic";
export declare class AlModal extends HTMLElement {
	static get observedAttributes(): string[];
	private previouslyFocused;
	private closeTimer;
	private isActive;
	private boundKeydown;
	private boundBackdropClick;
	private boundCloseClick;
	private boundSlotChange;
	constructor();
	connectedCallback(): void;
	disconnectedCallback(): void;
	attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null): void;
	get open(): boolean;
	set open(value: boolean);
	get size(): string;
	set size(value: string);
	get closable(): boolean;
	set closable(value: boolean);
	get backdropDismiss(): boolean;
	set backdropDismiss(value: boolean);
	get contained(): boolean;
	set contained(value: boolean);
	show(): void;
	hide(reason?: CloseReason): void;
	private activate;
	private deactivate;
	private updateUi;
	private get modalId();
	private hasAssignedNodes;
	private handleCloseClick;
	private handleBackdropClick;
	private handleKeydown;
	private getFocusableElements;
	private focusInitial;
	private trapFocus;
	private isNodeInsideModal;
	private lockScroll;
}

export {};
