// Generated by dts-bundle-generator v9.5.1

export declare class AlButton extends HTMLElement {
	static get observedAttributes(): string[];
	constructor();
	get variant(): string;
	set variant(value: string);
	get size(): string;
	set size(value: string);
	get disabled(): boolean;
	set disabled(value: boolean);
	get loading(): boolean;
	set loading(value: boolean);
	get fullWidth(): boolean;
	set fullWidth(value: boolean);
	connectedCallback(): void;
	attributeChangedCallback(): void;
	private render;
}
export declare class AlAccordion extends HTMLElement {
	static get observedAttributes(): string[];
	constructor();
	connectedCallback(): void;
	disconnectedCallback(): void;
	get multiple(): boolean;
	set multiple(value: boolean);
	attributeChangedCallback(): void;
	private handleToggle;
	private updateItems;
}
export declare class AlAccordionItem extends HTMLElement {
	static get observedAttributes(): string[];
	private headerButton;
	constructor();
	connectedCallback(): void;
	disconnectedCallback(): void;
	get title(): string;
	set title(value: string);
	get open(): boolean;
	set open(value: boolean);
	attributeChangedCallback(name: string): void;
	toggle(): void;
	setOpen(open: boolean): void;
}

export {};
